# Generated by Django 2.0.7 on 2018-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='slotstatus',
            options={'verbose_name': 'Slot Status', 'verbose_name_plural': 'Slot Status'},
        ),
        migrations.AddField(
            model_name='clients',
            name='Time_Left',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
