# Generated by Django 2.0.7 on 2018-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180927_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.IntegerField(),
        ),
    ]
