# Generated by Django 2.0.7 on 2018-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180928_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Device_Name',
            field=models.CharField(max_length=255, null=True, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='MAC_Address',
            field=models.CharField(max_length=255, null=True, verbose_name='MAC'),
        ),
    ]
