# Generated by Django 2.0.7 on 2018-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180929_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstatus',
            name='Client',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='slotstatus',
            name='Status',
            field=models.CharField(max_length=15),
        ),
    ]
