# Generated by Django 2.0.7 on 2018-09-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180929_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotspot_Name', models.CharField(max_length=255)),
                ('Hotspot_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Hotspot_ID', models.CharField(max_length=255)),
                ('Slot_Timeout', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
