# Generated by Django 2.0.7 on 2018-09-29 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 1, 50, 52, 387265)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], default='Disconnected', max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 1, 50, 52, 387265)),
        ),
        migrations.AlterField(
            model_name='slotstatus',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=15),
        ),
    ]
