# Generated by Django 2.0.7 on 2018-09-29 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180930_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 1, 58, 1, 811794)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.DurationField(),
        ),
    ]
