# Generated by Django 2.0.7 on 2018-09-29 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180930_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 2, 5, 37, 916515)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.DurationField(default=datetime.timedelta(0, 1200)),
        ),
    ]
