# Generated by Django 2.0.7 on 2018-09-29 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180930_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 2, 7, 29, 881969)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.DurationField(default=1200),
        ),
    ]
