# Generated by Django 2.0.7 on 2018-09-29 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180930_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Time_Left',
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 2, 10, 13, 278160)),
        ),
    ]
