# Generated by Django 2.0.7 on 2018-09-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180930_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Last_Update',
        ),
    ]
