# Generated by Django 2.0.7 on 2018-09-29 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_clients_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Time_Left',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 18, 43, 34, 635928, tzinfo=utc)),
        ),
    ]
