# Generated by Django 2.0.7 on 2018-09-29 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180930_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 19, 30, 52, 263331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Time_Left',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
