# Generated by Django 2.0.7 on 2018-10-01 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180930_0330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlotStatus',
            new_name='CoinSlot',
        ),
        migrations.AlterModelOptions(
            name='coinslot',
            options={'verbose_name': 'Coin Slot', 'verbose_name_plural': 'Coin Slot'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 28, 2, 465985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Paused', 'Paused')], default='Disconnected', max_length=255),
        ),
    ]
