# Generated by Django 2.0.7 on 2018-10-03 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181003_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Client', models.CharField(max_length=50)),
                ('Denomination', models.IntegerField()),
                ('Slot_No', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledger',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 17, 8, 19, 80944, tzinfo=utc)),
        ),
    ]
