# Generated by Django 2.0.7 on 2018-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181004_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Base_Value',
            field=models.IntegerField(default=6, verbose_name='Minutes/Peso'),
            preserve_default=False,
        ),
    ]
