# Generated by Django 2.0.7 on 2018-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_settings_base_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(max_length=15)),
                ('Total_Coins', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coin Queue',
                'verbose_name_plural': 'Coin Queue',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='Base_Value',
            field=models.IntegerField(verbose_name='Minutes / Peso'),
        ),
    ]
