# Generated by Django 2.0.7 on 2018-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181007_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinqueue',
            name='Client',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coinqueue',
            name='Total_Coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
