# Generated by Django 2.1.7 on 2019-02-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_coinslot_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Inactive_Timeout',
            field=models.IntegerField(default=15, help_text='Timeout before an idle client (status = Disconnected) is removed from the client list. (Minutes)', verbose_name='Inactive Timeout'),
            preserve_default=False,
        ),
    ]
