# Generated by Django 2.1.7 on 2019-02-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_settings_inactive_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Discon_Update',
            field=models.DateTimeField(null=True),
        ),
    ]
