# Generated by Django 2.1.7 on 2019-02-23 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_clients_discon_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 2, 53, 38, 576755, tzinfo=utc)),
        ),
    ]
