# Generated by Django 2.1.7 on 2019-02-23 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190223_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Discon_Update',
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 7, 41, 57, 686232, tzinfo=utc)),
        ),
    ]
