# Generated by Django 2.1.7 on 2019-02-27 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190223_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 18, 56, 10, 497231, tzinfo=utc)),
        ),
    ]
