# Generated by Django 2.1.7 on 2019-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190228_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Coinslot_Pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coinslot Pin'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Light_Pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Light Pin'),
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='Client',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
