# Generated by Django 2.1.7 on 2019-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190319_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denom', models.IntegerField(help_text='Enter coin denomination.', verbose_name='Denomination')),
                ('Minutes', models.IntegerField(help_text='Coin value in minutes.')),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='Coinslot_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry pi GPIO.BCM numbering.', null=True, verbose_name='Coinslot Pin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Light_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry pi GPIO.BCM numbering.', null=True, verbose_name='Light Pin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Slot_Timeout',
            field=models.IntegerField(help_text='Slot timeout in seconds.'),
        ),
    ]
