# Generated by Django 2.1.7 on 2019-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190320_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Rate_Type',
            field=models.CharField(choices=[('auto', 'Minutes/Peso'), ('manual', 'Custom Rate')], default='auto', max_length=25),
        ),
    ]
