# Generated by Django 2.1.7 on 2019-04-14 19:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190320_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='BG_Image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Settings.get_image_path),
        ),
    ]
