# Generated by Django 2.1.7 on 2019-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_settings_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='Hotspot_ID',
        ),
        migrations.AddField(
            model_name='settings',
            name='Device_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
