# Generated by Django 2.1.7 on 2019-05-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190504_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='Device_ID',
        ),
    ]
