# Generated by Django 2.1.7 on 2019-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_settings_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Ethernet_MAC', models.CharField(blank=True, max_length=50, null=True)),
                ('Wlan_MAC', models.CharField(blank=True, max_length=50, null=True)),
                ('Device_SN', models.CharField(blank=True, max_length=50, null=True)),
                ('Activation_Status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
