# Generated by Django 2.1.7 on 2019-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='MAC_Address',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='MAC'),
            preserve_default=False,
        ),
    ]
