# Generated by Django 2.1.7 on 2019-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190722_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voucher_code', models.CharField(max_length=20, unique=True)),
                ('Voucher_status', models.CharField(max_length=25)),
                ('Voucher_client', models.CharField(blank=True, max_length=50, null=True)),
                ('Voucher_create_date_time', models.DateTimeField()),
                ('Voucher_used_date_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Vouchers',
                'verbose_name': 'Vouchers',
            },
        ),
    ]
