# Generated by Django 2.1.7 on 2019-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_create_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_used_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
