# Generated by Django 2.1.7 on 2019-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20191006_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='Voucher_time_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_status',
            field=models.CharField(choices=[('Used', 'Used'), ('Not Used', 'Not Used'), ('Expired', 'Expired')], max_length=25),
        ),
    ]
