# Generated by Django 2.1.7 on 2019-10-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20191007_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinqueue',
            name='Total_Time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Minutes',
            field=models.DurationField(help_text='Coin value in minutes.'),
        ),
    ]
