# Generated by Django 2.1.7 on 2019-10-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20191007_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Base_Value',
            field=models.DurationField(verbose_name='Minutes / Peso'),
        ),
    ]
