# Generated by Django 2.2.7 on 2019-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20191007_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Coinslot_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry/orange pi GPIO.BOARD pinout.', null=True, verbose_name='Coinslot Pin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Light_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry/orange pi GPIO.BOARD pinout.', null=True, verbose_name='Light Pin'),
        ),
    ]
