# Generated by Django 2.2.7 on 2019-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20191124_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='BG_Image',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Base_Value',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Coinslot_Pin',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Hotspot_Address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Hotspot_Name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Inactive_Timeout',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Light_Pin',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Rate_Type',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Slot_Timeout',
        ),
    ]
