# Generated by Django 2.2.7 on 2019-11-24 15:44

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20191124_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='BG_Image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Settings.get_image_path),
        ),
        migrations.AddField(
            model_name='settings',
            name='Base_Value',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Minutes / Peso'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Coinslot_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry/orange pi GPIO.BOARD pinout.', null=True, verbose_name='Coinslot Pin'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Hotspot_Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='Hotspot_Name',
            field=models.CharField(default='OJO', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='Inactive_Timeout',
            field=models.IntegerField(default=15, help_text='Timeout before an idle client (status = Disconnected) is removed from the client list. (Minutes)', verbose_name='Inactive Timeout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='Light_Pin',
            field=models.IntegerField(blank=True, help_text='Please refer raspberry/orange pi GPIO.BOARD pinout.', null=True, verbose_name='Light Pin'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Pause_Resume_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables pause/resume function', verbose_name='Enable Pause/Resume'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Rate_Type',
            field=models.CharField(choices=[('auto', 'Minutes/Peso'), ('manual', 'Custom Rate')], default='auto', help_text='Select "Minutes/Peso" to use  Minutes / Peso value, else use "Custom Rate" to manually setup Rates based on coin value.', max_length=25),
        ),
        migrations.AddField(
            model_name='settings',
            name='Redir_Url',
            field=models.CharField(blank=True, help_text='Redirect url after a successful login. If not set, will default to the timer page.', max_length=255, null=True, verbose_name='Redirect URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Slot_Timeout',
            field=models.IntegerField(default=15, help_text='Slot timeout in seconds.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='Vouchers_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables voucher module', verbose_name='Enable Vouchers'),
        ),
    ]
