# Generated by Django 2.2.7 on 2019-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20191124_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Pause_Resume_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables pause/resume function', verbose_name='Pause/Resume'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Vouchers_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables voucher module', verbose_name='Vouchers'),
        ),
    ]
