# Generated by Django 2.2.7 on 2019-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20191125_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
