# Generated by Django 2.2.7 on 2019-11-27 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20191127_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
