# Generated by Django 2.2.7 on 2019-11-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20191127_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Last_Update',
            new_name='Last_Updated',
        ),
    ]
