# Generated by Django 2.2.7 on 2019-11-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20191127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(),
        ),
    ]
