# Generated by Django 2.2.7 on 2019-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20191127_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
