# Generated by Django 2.2.7 on 2019-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20191127_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinslot',
            name='Status',
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(),
        ),
    ]
