# Generated by Django 2.2.7 on 2020-01-08 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20191127_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
