# Generated by Django 2.2.7 on 2020-01-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20200108_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
