# Generated by Django 2.2.7 on 2020-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20200108_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Device_Name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device'),
        ),
    ]
