# Generated by Django 2.2.7 on 2020-01-08 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20200109_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Created',
        ),
        migrations.AddField(
            model_name='clients',
            name='Connected_On',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
