# Generated by Django 2.2.7 on 2020-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20200109_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Connected_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
