# Generated by Django 2.2.7 on 2020-01-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_clients_expire_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinslot',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=15),
        ),
    ]
