# Generated by Django 2.2.7 on 2020-01-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_coinslot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinslot',
            name='Status',
        ),
    ]
