# Generated by Django 2.2.7 on 2020-01-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_remove_coinslot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Rate', models.IntegerField(blank=True, help_text='Specify global internet upload bandwidth in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Upload Bandwidth')),
                ('Download_Rate', models.IntegerField(blank=True, help_text='Specify global internet download bandwidth in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Download Bandwidth')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
        ),
    ]
