# Generated by Django 2.2.7 on 2020-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Download_Rate',
            field=models.IntegerField(blank=True, help_text='Specify client internet download bandwidth in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Download Bandwidth'),
        ),
        migrations.AddField(
            model_name='clients',
            name='Upload_Rate',
            field=models.IntegerField(blank=True, help_text='Specify client internet upload bandwidth in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Upload Bandwidth'),
        ),
    ]
