# Generated by Django 3.0.3 on 2020-03-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20200125_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Wlan_MAC',
        ),
        migrations.AddField(
            model_name='device',
            name='ca',
            field=models.CharField(default=1, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='pub_rsa',
            field=models.TextField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
