# Generated by Django 3.0.3 on 2020-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20200304_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ca',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='pub_rsa',
            field=models.TextField(),
        ),
    ]
