# Generated by Django 3.0.3 on 2020-03-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20200304_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Activation_Status',
        ),
    ]
