# Generated by Django 3.0.3 on 2020-03-06 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_device_activation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
