# Generated by Django 3.0.3 on 2020-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20200306_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
