# Generated by Django 3.0.3 on 2020-03-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_whitelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'Device Whitelist', 'verbose_name_plural': 'Device Whitelist'},
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_status',
            field=models.CharField(choices=[('Used', 'Used'), ('Not Used', 'Not Used'), ('Expired', 'Expired')], default='Not Used', max_length=25, verbose_name='Status'),
        ),
    ]
