# Generated by Django 3.0.8 on 2020-07-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20200307_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinqueue',
            name='Total_Time',
        ),
    ]
