# Generated by Django 3.0.8 on 2020-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_remove_coinqueue_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='Pulse',
            field=models.IntegerField(blank=True, help_text='Coinslot pulse count corresponding to coin denomination. Leave it blank for promotional rates.', null=True),
        ),
    ]
