# Generated by Django 3.0.8 on 2020-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20200714_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=False)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='OneSignal App ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='OneSignal API Key')),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_message', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_trigger_time', models.DurationField(blank=True, help_text='Notification will fire when time is equal to the specified trigger time. Format: hh:mm:ss', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device Settings', 'verbose_name_plural': 'Device Settings'},
        ),
        migrations.AddField(
            model_name='clients',
            name='Notification_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Subcription ID'),
        ),
        migrations.AddField(
            model_name='clients',
            name='Notified_Flag',
            field=models.BooleanField(default=False),
        ),
    ]
