# Generated by Django 3.0.8 on 2020-08-09 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20200809_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Hardware Setting', 'verbose_name_plural': 'Hardware Settings'},
        ),
        migrations.AlterModelOptions(
            name='pushnotifications',
            options={'verbose_name': 'Push Notifications Setting', 'verbose_name_plural': 'Push Notification Settings'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Wifi Setting', 'verbose_name_plural': 'Wifi Settings'},
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_trigger_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Notification will fire when time is equal to the specified trigger time. Format: hh:mm:ss', null=True),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Minutes',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Internet access duration in hh:mm:ss format', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_time_value',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Time value in minutes.', null=True, verbose_name='Time Value'),
        ),
    ]
