# Generated by Django 3.0.8 on 2020-08-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20200809_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Connected_Flag',
            field=models.BooleanField(default=False),
        ),
    ]
