# Generated by Django 3.0.8 on 2020-08-31 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_clients_connected_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Expire_On',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
