# Generated by Django 3.0.8 on 2020-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_auto_20200901_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Expire_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
