# Generated by Django 3.0.8 on 2020-09-01 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_auto_20200901_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Sync_Time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
