# Generated by Django 3.0.8 on 2020-09-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_device_sync_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Connected_On',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='Last_Updated',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='Status',
        ),
    ]
