# Generated by Django 3.0.8 on 2020-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20200902_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Connected_Flag',
        ),
    ]
