# Generated by Django 3.0.8 on 2020-09-06 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_remove_clients_connected_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 5, 49, 20, 842494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Notification_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification ID'),
        ),
    ]
