# Generated by Django 3.0.8 on 2020-09-06 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20200906_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Date_Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
