# Generated by Django 3.0.8 on 2020-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_auto_20200906_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Disable_Pause_Time',
            field=models.DurationField(blank=True, help_text='Disables Pause time button if remaining time is less than the specified time.', null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Pause_Resume_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables pause/resume function.', verbose_name='Pause/Resume'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Vouchers_Flg',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='Enables voucher module.', verbose_name='Vouchers'),
        ),
    ]
