# Generated by Django 3.0.8 on 2020-10-02 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20201003_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Disable_Pause_Time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Disables Pause time button if remaining time is less than the specified time hh:mm:ss format.', null=True),
        ),
    ]
