# Generated by Django 3.0.8 on 2020-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20201003_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='DNS_1',
            field=models.GenericIPAddressField(default='8.8.8.8', verbose_name='DNS'),
        ),
        migrations.AddField(
            model_name='network',
            name='DNS_2',
            field=models.GenericIPAddressField(blank=True, default='8.8.4.4', null=True, verbose_name='Alternate DNS'),
        ),
        migrations.AddField(
            model_name='network',
            name='Netmask',
            field=models.GenericIPAddressField(default='255.255.255.0'),
        ),
        migrations.AddField(
            model_name='network',
            name='Server_IP',
            field=models.GenericIPAddressField(default='10.0.0.1'),
        ),
    ]
