# Generated by Django 3.0.8 on 2020-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_auto_20201003_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='DNS_1',
            field=models.GenericIPAddressField(default='8.8.8.8', protocol='IPv4', verbose_name='DNS'),
        ),
        migrations.AlterField(
            model_name='network',
            name='DNS_2',
            field=models.GenericIPAddressField(blank=True, default='8.8.4.4', null=True, protocol='IPv4', verbose_name='Alternate DNS'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Netmask',
            field=models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Server_IP',
            field=models.GenericIPAddressField(default='10.0.0.1', protocol='IPv4'),
        ),
    ]
