# Generated by Django 3.0.8 on 2020-10-08 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20201004_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Hardware'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network'},
        ),
        migrations.AlterModelOptions(
            name='pushnotifications',
            options={'verbose_name': 'Push Notifications'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'Allowed Client', 'verbose_name_plural': 'Allowed Clients'},
        ),
        migrations.AlterField(
            model_name='network',
            name='Server_IP',
            field=models.GenericIPAddressField(default='10.0.0.1', protocol='IPv4', verbose_name='Server IP'),
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Message'),
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Title'),
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_trigger_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Notification will fire when time is equal to the specified trigger time. Format: hh:mm:ss', null=True, verbose_name='Notification Trigger'),
        ),
    ]
