# Generated by Django 3.0.8 on 2020-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_auto_20201009_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='DNS_2',
            field=models.GenericIPAddressField(blank=True, default='8.8.4.4', null=True, protocol='IPv4', verbose_name='DNS 2 (Optional)'),
        ),
    ]
