# Generated by Django 3.0.8 on 2020-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_auto_20201009_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='DNS_1',
            field=models.GenericIPAddressField(default='8.8.8.8', protocol='IPv4', verbose_name='DNS 1'),
        ),
    ]
