# Generated by Django 3.0.8 on 2020-11-30 06:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_auto_20201009_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinslot',
            name='Slot_Address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='Slot_ID',
            field=models.CharField(default=app.models.CoinSlot.generate_code, max_length=10, unique=True),
        ),
    ]
