# Generated by Django 3.0.8 on 2020-11-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_coinslot_slot_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Slot_Desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
    ]
